spring:
  application:
    name: transport-service
  datasource:
    url: jdbc:mysql://localhost:3306/transport
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
server:
  port: 0